# Generated by Django 5.0.2 on 2024-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_profile_customer_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
